version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "digidex-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kh1zqhqgixfl"
s3_prefix = "digidex-lambda"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
